#pragma once
#ifndef ETSPARSER_H
#define ETSPARSER_H

// Fichier : ETSParser.h
// GPA434 – Laboratoire 3
// Création :
// - E. Surprenant
// - M. Boudreau
// - 2020/11/01
// - - - - - - - - - - - - - - - - - - - - - - -
#pragma region Includes
#include "IParser.h"
#pragma endregion



class ETSParser : public IParser
{


#pragma region Getters/Setters
public:
	void SetQCleanList() {
		mQCleanList = QStringList{
"Bureau du registraire - logistique académique",
"                                                          HORAIRE HIVER 2021",
"Locaux A: bâtiment sud, 1100, Notre-Dame O.",
"                                                Locaux B: bâtiment nord, 1111, Notre-Dame O.",
"                                                Locaux D: bâtiment sud-ouest, 1219, rue William",
"                                                Locaux E: bâtiment ouest, 1220, Notre-Dame O.",
"                                                                    AVIS IMPORTANT",
"                                                 Différents modes d'enseignement sont proposés",
"                                               P: présence - C: co-modal - D: distance - H: hybride",
"HEURE ACTIVITÉ Mode d'ens. LOCAL",
"Page : "
		};
	};
	
#pragma endregion

#pragma region Functions
protected:
	/// <summary>
	/// Remove all unwated string literals from text file generated by program.
	/// </summary>
	void CleanTextFile() final;

	//void ParseDataFromText(QList<QObject*>*) final;
	//void ParseDataFromText2(QList<QObject*>*) final;
	QList<QObject*> ParseDataFromText() final;

#pragma endregion

#pragma region Members
protected:
	
#pragma endregion

#pragma region Ctors/Dtors
public:
	ETSParser();
	~ETSParser() override;
	ETSParser(ETSParser const&) = default;
#pragma endregion

#pragma region Operators
	ETSParser& operator=(ETSParser const&) = default;
#pragma endregion




};
#endif // ETSPARSER_H