# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SemesterLogix
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += SOLUTION_DIR=R\"($(SolutionDir))\"
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += .
include(SemesterLogix.pri)
